package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
)

func Actionlint(src []byte) ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// Some error message contains absolute file paths. Replace them not to make the document depend
// on the current file system.

type state int

const (
	stateInit state = iota
	stateAnchor
	stateHeading
	stateInputHeader
	stateInputBlock
	stateAfterInput
	stateOutputHeader
	stateAfterOutput
	stateOutputBlock
	stateEnd
)

func (s state) String() string { _ = "STUB: not implemented"; return "" }

type Updater struct {
	prev, cur state
	lines     *bufio.Scanner
	out       bytes.Buffer
	heading   string
	input     bytes.Buffer
	lnum      int
	ids       map[string]int
	headings  map[string]int
	firstErr  error
}

func NewUpdater(in []byte) *Updater { _ = "STUB: not implemented"; return nil }

func (u *Updater) err(err error) { _ = "STUB: not implemented"; return }

func (u *Updater) End() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (u *Updater) PlaygroundLink(src []byte) string { _ = "STUB: not implemented"; return "" }

func (u *Updater) state(s state, reason string) { _ = "STUB: not implemented"; return }

func (u *Updater) Scan() bool { _ = "STUB: not implemented"; return false }

func (u *Updater) expect(states ...state) { _ = "STUB: not implemented"; return }

func (u *Updater) Update() { _ = "STUB: not implemented"; return }

// Validation

// State transition
//
//    backtrack
//    ┌───────┐
// ┌──▼─┐  ┌──┴───┐  ┌───────┐  ┌──────┐  ┌─────┐  ┌─────┐
// │init│─►│anchor│─►│heading│─►│input │─►│input│─►│after│────┐
// └────┘  │      │  │       │  │header│  │block│  │input│    │
//         └──▲┬──┘  └───────┘  └──▲───┘  └─────┘  └─────┘ ┌──▼───┐
//     next   ││            more   │            skip       │output│
//     section││            example│        ┌──────────────│header│
//            ││backtrack        ┌───┐  ┌───▼──┐  ┌──────┐ └──┬───┘
//            │└────────────────►│end│◄─│after │◄─│output│◄───┘
// ┌────┐     └──────────────────│   │  │output│  │block │
// │done│◄───────────────────────│   │  └──────┘  └──────┘
// └────┘                        └───┘
//

// Output block will be generated by actionlint

func Update(in []byte) ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

var stderr io.Writer = os.Stderr

func Main(args []string) error { _ = "STUB: not implemented"; return nil }

func main() {
	if err := Main(os.Args); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
